export enum ActionTypeKeys {
    REGISTER_INPROGRESS = 'REGISTER_INPROGRESS',
    REGISTER_SUCCESS = 'REGISTER_SUCCESS',
    REGISTER_FAILURE = 'REGISTER_FAILURE',
    LOGIN_INPROGRESS = 'LOGIN_INPROGRESS',
    LOGIN_SUCCESS = 'LOGIN_SUCCESS',
    LOGIN_FAILURE = 'LOGIN_FAILURE'
}
